const fs = require('fs');

const rawDemographics = `Carimbo de data/hora;Empresa;Endereço de e-mail;DADOS PESSOAIS - NOME:;ENDEREÇO:;TELEFONE (residencial):;TELEFONE (celular):;IDADE:;HABITAÇÃO;POSSUI COMPUTADOR/NOTEBOOK?;POSSUI INTERNET EM CASA?;ESCOLARIDADE;ESTUDANDO ATUALMENTE?;Se sim, qual???;ESTADO CIVIL;POSSUI FILHOS?;Se sim, quantos???;FILHOS (QUANTOS POR IDADE) [Menor que 4 anos];FILHOS (QUANTOS POR IDADE) [Entre 5 e 11 anos];FILHOS (QUANTOS POR IDADE) [Entre 12 e 18 anos];FILHOS (QUANTOS POR IDADE) [Acima de 18 anos];FILHOS (QUANTOS POR IDADE) [Não tenho];OUTROS DEPENDENTES (DESCREVER):;RENDA FAMILIAR;TENHO HARMONIA NO MEU LAR;"A RENDA FAMILIAR SUPRE TODAS AS
NECESSIDADES";EU GOSTO DE FICAR EM CASA;EM CASA NOS AJUDAMOS UNS AOS OUTROS;NAS HORAS VAGAS GOSTO DE ESTAR SEMPRE COM MINHA FAMILIA;PROCURO SEMPRE ESTAR ATUALIZADO COM AS NOTICIAS;GOSTO DE ESTUDAR , MANTENDO-ME SEMPRE ATUALIZADO;NO TRABALHO, EU ATUO NA AREA QUE SOU FORMADO;DESCREVA O QUE GOSTA DE FAZER NAS HORAS VAGAS:;SE FOSSE ESTUDAR, GOSTARIA DE FAZER OS SEGUINTES CURSOS:;QUAL SEU MAIOR SONHO:;QUAL O PRÓXIMO PASSO PARA BUSCAR MEU SONHO;Gênero;ANO
14/05/2025 16:33;Central Mesh São Paulo;;Fernanda;Rua Luis Gama;-;(11) 98459-6497;44;Própria;Sim;Sim;Ensino superior completo;Não;-;Casado;Sim;3;;1 filho(a);;2 filhos(as);;-;Acima de 5.000,00;Na maioria das vezes;Algumas Vezes;Sempre;Sempre;Sempre;Na maioria das vezes;Na maioria das vezes;Sempre;gosto de estar com familia;psicologia;ver meus filhos formados;orar;Feminino;2025
15/05/2025 13:59;Elasa;;jefferson;rua avaremotemo;nao tenho;11958789843;28;Própria;Não;Não;Ensino médio incompleto;Não;nao;Casado;Sim;1;;1 filho(a);;;;nao;1.000,00 à 2.000,00;Sempre;Nunca;Sempre;Sempre;Sempre;Sempre;Na maioria das vezes;Nunca;jogar bola;programaçao;dar vida melhor para familia;estudar;Masculino;2025`;

// Rather than reading the full huge CSV, I'll just structure src/data/mockData.ts for the user.
// The user wants me to clean out the data completely, and then they will upload their correct spreadsheets!
// "Limpe todas as configurações de planilhas deixe sem as conexões pois irei adicionar as planilhas corretas e as conexões corretas e testar para vermos se vai calcular corretamente"
